package visab2b.TestScript_API;

import com.intuit.karate.junit5.Karate;

class FeatureRunner {

    @Karate.Test
    Karate testUsers() {
        return Karate.run(
        		
              "Albania",
              "Argentina",
              "Azerbaijan",
              "GetAuditAPI"
        		
        		).relativeTo(getClass());
        
        

//        "Albania",
//        "Algeria",
//        "Angola",
//        "Antigua",
//        "Argentina",
//        "Armenia",
//        "Australia",
//        "Austria",
//        "Azerbaijan",
//        "Bahamas",
//        "Bahrain",
//        "BahrainAny",
//        "Bangladesh",
//        "Belarus",
//        "Belgium",
//        "Bermuda",
//        "Bolivia",
//        "BosniaandHerzegovina",
//        "Botswana",
//        "Brazil",
//        "BritishVirginIslands",
//        "BulgariaBGN",
//        "BulgariaEUR",
//        "Cambodia",
//        "CanadaCAD",
//        "CanadaUSD",
//        "CaymanIslands",
//        "Chile",
//        "China",
//        "Colombia",
//        "CostaRica",
//        "CoteDivoire",
//        "CroatiaEUR",
//        "CroatiaHR",
//        "Curacao",
//        "Cyprus",
//        "CzechRepublic",
//        "Denmark",
//        "DominicanRepublic",
//        "Ecuador",
//        "Egypt",
//        "El Salvador",
//        "Estonia",
//        "Finland",
//        "France",
//        "Georgia",
//        "Germany",
//        "Ghana",
//        "Greece",
//        "Guatemala",
//        "Guyana",
//        "Haiti",
//        "Honduras",
//        "HongKong",
//        "HungaryEUR",
//        "HungaryHUF",
//        "Iceland",
//        "Ireland",
//        "Israel",
//        "Italy",
//        "Jamaica",
//        "Japan",
//        "Jordan",
//        "Kazakhstan",
//        "Kenya",
//        "Kuwait",
//        "Laos",
//        "Latvia",
//        "Lebanon",
//        "Lithuania",
//        "Luxembourg",
//        "Maldives",
//        "Malta",
//        "Mauritius",
//        "Mexico",
//        "Mongolia",
//        "Morocco",
//        "Mozambique",
//        "Namibia",
//        "Netherlands",
//        "NewZealand",
//        "Nicaragua",
//        "Nigeria",
//        "Norway",
//        "Oman",
//        "Pakistan",
//        "Panama",
//        "Paraguay",
//        "Peru",
//        "Poland",
//        "Portugal",
//        "PuertoRico",
//        "Qatar",
//        "Romania",
//        "Saudi Arabia",
//        "Senegal",
//        "Serbia",
//        "Singapore",
//        "Slovakia",
//        "Slovenia",
//        "South Africa",
//        "South Korea",
//        "Spain",
//        "Sri Lanka",
//        "Sweden",
//        "Switzerland",
//        "Taiwan",
//        "Tanzania",
//        "Thailand",
//        "Trinidad and Tobago",
//        "Tunisia",
//        "Turkey",
//        "Turks and Caicos Islands",
//        "Uganda",
//        "Ukraine",
//        "United Arab Emirates",
//        "United Kingdom",
//        "United States",
//        "Uruguay",
//        "Vietnam",
//        "Zambia",
//        "GetAuditAPI"        
        
        
        
    }

}

